In [1]:
import numpy as np
np.__version__

'1.24.3'

## 메소드와 속성

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [3]:
a = np.array(0)

In [4]:
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [5]:
a = np.array([2, 4, 6])
a, a.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [6]:
a = [[1, 2, 3], [4, 5, 6]]
a

[[1, 2, 3], [4, 5, 6]]

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [8]:
a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] )
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [9]:
a.shape

(2, 2, 3)

In [10]:
a = np.array(3)
a, a.shape # 행렬아님

(array(3), ())

In [11]:
a = np.array([ 1, 3, 5, 7, 9 ])
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [12]:
a = np.array([[1,2,3], [4,5,6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [13]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

## size

In [14]:
a= np.array([1, 3, 5, 7, 9])

In [15]:
a = np.array([[1,2,3], [4,5,6]])

In [16]:
넘파이 배열

SyntaxError: invalid syntax (4044338956.py, line 1)

In [ ]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

In [ ]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape} 구조타입={type(myArr.shape)}, size={myArr.size}')

## myArr

In [ ]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

In [ ]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape} 구조타입 = {type(myArr2.shape)}, size = {myArr2.size}')

In [ ]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4 ],[10,20 ,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

In [ ]:
# 길이가 달라 에러 리턴
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape} 구조타입 = {type(myArr21.shape)}, size = {myArr21.size}')

## 넘파이 배열과 리스트와의 차이점

In [ ]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

In [ ]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

In [ ]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

In [ ]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

## dtype

In [ ]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

In [ ]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환
print(myArr_c, type(myArr_c), myArr_c.dtype)

In [ ]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

## Inf와 NaN

In [ ]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

In [ ]:
np.log(0)

In [ ]:
np.exp(-np.inf)

## 기술통계

In [ ]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [ ]:
np.mean(x)  # 평균

In [ ]:
np.var(x)  # 분산

In [ ]:
np.std(x)  # 표준 편차

In [ ]:
np.max(x)  # 최댓값

In [ ]:
np.min(x)  # 최소값

In [ ]:
np.median(x)  # 중앙값

## 사분위수

In [ ]:
np.percentile(x, 0)  # 최소값

In [ ]:
np.percentile(x, 25)  # 1사분위 수

In [ ]:
np.percentile(x, 50)  # 2사분위 수

In [ ]:
np.percentile(x, 75)  # 3사분위 수

In [ ]:
np.percentile(x, 100)  # 최댓값

## 넘파이 함수로 배열 만들기

In [ ]:
# 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype)

In [ ]:
print(np.ones((2,4)), np.ones((2,4)).dtype)

In [ ]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype)

In [ ]:
print(np.zeros(10), np.zeros(10).dtype)

In [ ]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

In [ ]:
# 메모리가 비어있음
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))

In [ ]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

In [ ]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

In [ ]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

In [ ]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

## reshape 구조의 재배열

In [ ]:
arr, arr.data, arr.shape

In [ ]:
arr = arr.reshape(10, 5)
arr, arr.ndim, arr.shape

In [ ]:
arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape

In [ ]:
# 2차원 -> 1차원
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

In [ ]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

In [ ]:
print(np.arange(2,101,2).reshape(5,10))

In [ ]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(-1, 1)
arr4, arr4.ndim, arr4.shape

In [ ]:
# 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(5, 4)

In [ ]:
# 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(-1, 4)
# rehsape -1은, 행무관하고 n개의 컬럼을 만든다

In [ ]:
# 사이즈가 맞아야 한다.
# np.arange(1, 21).reshape(-1, 7)

In [ ]:
a = np.arange(12)
a, a.shape

In [ ]:
# 원본 값이 바뀜
a.shape = 2, -1
a, a.shape

In [ ]:
a.shape = 3, -1
a, a.shape

In [ ]:
a.shape = -1, 1
a, a.shape

In [ ]:
a.shape = -1, 2
a, a.shape

In [ ]:
a.shape = -1, 3
a, a.shape

In [ ]:
# flatten
a.shape = -1
a, a.shape

## 넘파이배열의 자료형 형변환

In [ ]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

In [ ]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

In [ ]:
# 실수형, 3행 3열
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

In [ ]:
# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

In [ ]:
# 정수형 => 문자열
matrix.astype('<U5')

In [ ]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

In [ ]:
# 불린 -> 정수
matrix2.astype(int)

In [ ]:
# 불린형 -> 문자열
matrix2.astype('<U5')

In [ ]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

In [ ]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가

In [ ]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

## 넘파이 배열의 인덱싱

## 1D array

In [ ]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

In [ ]:
a[0]

In [ ]:
a[2]

In [ ]:
a[4]

In [ ]:
a[-1]

In [ ]:
a[-3]

In [ ]:
a[-5]

In [ ]:
a[[0, 2, 4]]

In [ ]:
a

In [ ]:
# 행렬 구조로 인덱싱도 가능하다
i = np.array([[1,3], [4,2]])
i

In [ ]:
# 넘파이배열1을 넘파이배열2로 인덱싱하는 경우. 넘파이배열2는 인덱스 번호로 인식
a[i]

In [ ]:
a[2] = 0
a

In [ ]:
a[1] += 2
a

## 2D array

In [ ]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

In [ ]:
a[0]

In [ ]:
a[1]

In [ ]:
a[2]

In [ ]:
a[-1]

In [ ]:
a[-2]

In [ ]:
a[-3]

In [ ]:
a

In [ ]:
a[0, 0]

In [ ]:
a[0, 1]

In [ ]:
a[0, 2]

In [ ]:
a[1, 0]

In [ ]:
a[1, 1]

In [ ]:
a[1, 2]

In [ ]:
a[2, 0]

In [ ]:
a[2, 1]

In [ ]:
a[2, 2]

In [ ]:
a[-1, 0]

In [ ]:
a = np.arange(15).reshape(3, -1)
a

In [ ]:
a[1] = [1, 3, 5, 7, 9]
a

In [ ]:
a[0] += [1, 2, 3, 4, 5]
a

In [ ]:
matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3,4)

matrix_a, matrix_b

In [ ]:
# 1차원에서 첫 요소와 마지막 요소
matrix_a[0], matrix_a[-1]

In [ ]:
# 2차원에서 1번째행 1번째열
matrix_b[0, 0]

In [ ]:
matrix_b[0][0]

In [ ]:
matrix_b

In [ ]:
# 2차원 마지막행 마지막열 -> 3행 4열
matrix_b[-1,-1]

In [ ]:
matrix_b[-1][-1]

In [ ]:
matrix_b[2][3]

In [ ]:
# matrix_b에서 3번째행 1번째열의값을 100으로 변경해보자
matrix_b[2,0] = 100
matrix_b

In [ ]:
넘파이배열 슬라이싱

In [ ]:
1D array

In [ ]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

In [ ]:
a[:]

In [ ]:
 a[1:]

In [ ]:
a[-1:]

In [ ]:
a[:3]

In [ ]:
a[:-1]

In [ ]:
a[1:4]

In [ ]:
a[1:-1]

In [ ]:
a = np.arange(10)
a

In [ ]:
a[::2]

In [ ]:
a[::5]

In [ ]:
a[::-1]

In [ ]:
# 홀수
a[1::2]

In [ ]:
a[3::2]

In [ ]:
a[:-2:2]

In [ ]:
a[:-6:2]

In [ ]:
a[2:-2:2]

## 2D array

In [ ]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

In [ ]:
a[:]

In [ ]:
a[1:]

In [ ]:
a[3:]

In [ ]:
a[-1:]

In [ ]:
a[-3:]

In [ ]:
a[:0]

In [ ]:
a[:2]

In [ ]:
a[:-1]

In [ ]:
a[:-3]

In [ ]:
a[1:-1]

In [ ]:
a[:, :]

In [ ]:
a[:, 1:]

In [ ]:
a[:, 3:]

In [ ]:
a[:, -1:]

In [ ]:
a[:, -4:]

In [ ]:
a[:, :1]

In [ ]:
a[:, :5]

In [ ]:
a

In [ ]:
a[:, :-1]

In [ ]:
a[:, :-2]

In [ ]:
a[:, 0:1]

In [ ]:
a[:, 2:3]

In [ ]:
a[:, 1:-1]

In [ ]:
a = np.arange(10, 100).reshape(9, 10)
a

In [ ]:
a[2:5, :]

In [ ]:
a[:, 2:5]

In [ ]:
a[2:5, 2:5]

In [ ]:
a[::2, ::2]

In [ ]:
a

In [ ]:
a[::-1, ::-1]

In [ ]:
matrix_c = np.arange(1, 26).reshape(5,5)
matrix_c, type(matrix_c), matrix_c.ndim

In [ ]:
# 1차원 슬라이싱, 1행만 출력
matrix_c[0, :], matrix_c[0]

In [ ]:
# 2차원 슬라이싱, 1번째행 2번째행 출력
matrix_c[0:2, :], matrix_c[0:2]

In [ ]:
# 1번째열만 출력
matrix_c[:, 0]

In [ ]:
# 3,4 번째열만 출력
matrix_c[:, 2:4]

In [ ]:
# 특정행의 특정열 슬라이싱
matrix_c[0:3, 0:2]

In [ ]:
# 홀수번째 행만 출력
matrix_c[::2, ::]

In [ ]:
# 짝수번쨰행 + 홀수번째열
matrix_c[1::2, ::2]

In [ ]:
# 리버스 인덱싱
print(matrix_c[::-1, ::]) # 행 뒤집기
print(matrix_c[::, ::-1]) # 열 뒤집기

## 전치행렬

In [ ]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

In [ ]:
# 2행 3열로 변환
print(matrix_d.T)

In [ ]:
# reshape과 transpose은 값이 다름을 유의
print(matrix_d.reshape(2,3)) 

## 난수로 구성된 넘파이 배열

In [ ]:
np.random?

In [ ]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

In [ ]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5))

## 섞기

In [ ]:
np.random.shuffle?

In [ ]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

In [ ]:
np.random.shuffle(matrix_e)
matrix_e

### Quiz : 1~46까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라

In [ ]:
num = np.arange(1,47)
np.random.shuffle(num)
num[:6]

In [ ]:
np.random.randint(1,47,6)

### 실수 난수

In [17]:
np.random.randn?

In [18]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

array([-1.758368  , -1.75042292,  0.76772893, -1.09169277, -1.25885288,
        0.3849384 , -1.32735376, -0.30299693, -0.21050651, -0.09295987])

In [19]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[ 1.27893136,  0.19426965, -1.6946658 ,  0.69595563],
       [-1.03918679, -1.53596694, -0.89273269,  0.32504192],
       [-1.65329446,  1.64284282, -0.66188002, -0.51087978],
       [-0.35792719,  1.28143191, -0.64821483,  2.58157123]])

In [20]:
matrix1.max(), matrix1.min()

(0.7677289282617743, -1.7583680010481664)

### 집계함수에서의 축

In [21]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[40, 47, 40, 21, 30],
       [ 6, 42,  7, 23, 12],
       [20, 40, 13, 25, 23],
       [13,  6, 41, 19, 29],
       [24,  9, 44, 27,  3]])

In [22]:
np.sum(m1, axis=0) # (x)행 합계

array([103, 144, 145, 115,  97])

In [23]:
np.sum(m1, axis=1) # 열(y) 합계

array([178,  90, 121, 108, 107])

In [24]:
# 1번째행의 합계는
np.sum(m1[0,:], axis=0) # x축(행 방향) 합계

178

### np.sort()

In [25]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[33, 48, 26],
       [49,  7, 10],
       [27, 25, 34],
       [20, 13, 31]])

In [26]:
np.sort?

In [27]:
np.sort(m2, axis=0) # 행방향 오름차순(요소별로)

array([[20,  7, 10],
       [27, 13, 26],
       [33, 25, 31],
       [49, 48, 34]])

In [28]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다

array([[20, 13, 31],
       [27, 25, 34],
       [49,  7, 10],
       [33, 48, 26]])

In [29]:
np.sort(m2, axis=1) # 열방향 오름차순

array([[26, 33, 48],
       [ 7, 10, 49],
       [25, 27, 34],
       [13, 20, 31]])

### 인덱스 소팅

In [30]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값 

array([2, 1, 0])

In [31]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])

### 넘파이 배열 요소 추가와 삭제

In [32]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [34]:
m3[-1]

10

In [35]:
np.insert?

In [36]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [37]:
np.insert(m3, len(m3), 500) 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [38]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [40]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [41]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [42]:
m4.shape, m4.shape[1], len(m4)

((3, 3), 3, 3)

In [43]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [44]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [45]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

### 배열 합치기

In [47]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [49]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [50]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.sh

AttributeError: 'numpy.ndarray' object has no attribute 'sh'

In [51]:
f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [52]:
f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

### boolean indexing, mask

In [53]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [55]:
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
(matrix > 10).sum()

10

### Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라

In [57]:
num = np.random.randint(1,100,30)
(num > 30) & (num < 70)

array([ True,  True, False,  True,  True, False, False, False, False,
        True,  True, False, False, False, False, False, False,  True,
       False, False, False, False,  True, False,  True, False,  True,
        True, False,  True])

In [58]:
num = np.random.randint(1,100,30)
num, num[(num > 30) & (num < 70)]

(array([92, 15, 43, 55, 20, 74, 49, 51,  4, 77, 53, 87, 88, 36, 48,  4, 89,
        64, 83, 53, 10, 61, 38, 37, 37, 87, 32, 91,  7, 36]),
 array([43, 55, 49, 51, 53, 36, 48, 64, 53, 61, 38, 37, 37, 32, 36]))

In [59]:
# ~ 은 reverse를 의미
num[~(num > 30) & (num < 70)]

array([15, 20,  4,  4, 10,  7])

In [60]:
# 10보다 작거나 90보다 큰 수,
num[(num < 10) | (num > 90)]

array([92,  4,  4, 91,  7])

In [61]:
 num[~(num < 10) | (num > 90)]

array([92, 15, 43, 55, 20, 74, 49, 51, 77, 53, 87, 88, 36, 48, 89, 64, 83,
       53, 10, 61, 38, 37, 37, 87, 32, 91, 36])

### fancy indexing(filtering)

In [62]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([22, 57, 13, 57, 89, 55, 35, 57, 81, 98, 14, 21, 55, 41, 11, 22, 70,
        48, 60, 24, 32, 84, 52, 29, 60, 35, 44, 94, 99, 19]),
 array([22, 13, 57, 14, 32]))

### np.where()를 이용한 필터링


In [ ]:
np.where?

In [63]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [64]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4]),))